code --install-extension almenon.arepl
code --install-extension batisteo.vscode-django
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension rebornix.ruby
code --install-extension remimarsal.prettier-now
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sissel.shopify-liquid
code --install-extension syler.sass-indented
code --install-extension wingrunr21.vscode-ruby
code --install-extension Wscats.eno
code --install-extension xabikos.JavaScriptSnippets
